### PR TITLE
AbetMiner / MinStake / TestNet / AuthHelper

### PR DESCRIPTION
**Pull request by MotoAcidic**

### CODE REVIEW

**Comment by MotoAcidic** [comment]
@SloRunner Take a look and see if anything is missing.

**Comment by MotoAcidic** [comment]
Just fixed that.

**Comment by MotoAcidic** [comment]
@SloRunner Check out the Authentication Helper and double check if you can.

**Comment by SloRunner** [comment]
maybe add second min stake and force it after certain block? so there is smooth transition between them

**Pull request merged**
